//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF02
{
    using System;
    using System.Collections.Generic;
    
    public partial class 員工
    {
        public string 員工編號 { get; set; }
        public string 姓名 { get; set; }
        public string 信箱 { get; set; }
        public Nullable<int> 薪資 { get; set; }
        public Nullable<System.DateTime> 雇用日期 { get; set; }
        public Nullable<bool> 是否已婚 { get; set; }
    }
}
