//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NBAWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NBA_Player
    {
        [Required(ErrorMessage="必填")]
        public string Id { get; set; }
        [Required(ErrorMessage = "必填")]
        public string No { get; set; }
        [Required(ErrorMessage = "必填")]
        public string Name { get; set; }
        [Required(ErrorMessage = "必填")]
        public Nullable<bool> Male { get; set; }
        [Required(ErrorMessage = "必填")]
        public string Team { get; set; }
        [Required(ErrorMessage = "必填")]
        public Nullable<int> Pts { get; set; }
        [Required(ErrorMessage = "必填")]
        public Nullable<int> Rbs { get; set; }
        [Required(ErrorMessage = "必填")]
        public Nullable<int> Asts { get; set; }
        [Required(ErrorMessage = "必填")]
        public Nullable<System.DateTime> GameDate { get; set; }
    }
}
